zuul:
  host:
    socket-timeout-millis: 500000
    connect-timeout-millis: 500000
hystrix:
  command:
    default:
      execution:
#        enabled: false
        isolation:
#          strategy: THREAD
          thread:
            timeoutInMilliseconds: 400000

mail:
  domain: gmail.com
