mail:
  domain: gmail.com
hystrix:
  command:
    default:
      execution:
#        enabled: false
        isolation:
#          strategy: THREAD
          thread:
            timeoutInMilliseconds: 400000
