server:
  port: 8087 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  basic:
    enabled: false
# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_indiana_oauth2
    username: root
    password: pgi1979
    driver-class: com.mysql.jdbc.Driver
   
   
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none


mongo: 
  database: dominus
  host: localhost
  password:
  port: 27017
  username:

---

authserver:
  hostname: localhost
  port: 8899
  contextPath: userauth

spring:
  profiles: docker
  oauth2:
    resource:
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
    client:
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/token
      userAuthorizationUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/oauth/authorize
    clientId: clientapp
    
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
defaultZone: http://localhost:8761/eureka/
