server:
  port: 8891
  contextPath: /gofiliate 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
spring:
  profiles: docker
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
