--- 
eureka: 
  client: 
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka/"
  instance: 
    preferIpAddress: true
mongo: 
  database: dominus
  host: localhost
  password:
  port: 27017
  username:
server: 
  port: 8080
spring: 
  profiles: docker
