server:
  port: 8761

spring:
      config:
            name: webservice-registry
      application:
            name: webservice-registry
      cloud:
            config:
                failFast: true
                discovery:
                  enabled: true
                uri:
                     #  http://10.3.1.187:8888/
                      http://localhost:8888/
                      
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  
   
